// Regenerates src/chain/policy-wallet-abi.ts from the Foundry artifact (contracts/out, gitignored).
// Run `forge build` first. CI regenerates it after `forge build` and fails on a diff (Story 2.6).
import { readFileSync, writeFileSync } from "node:fs";

const artifactUrl = new URL("../../../contracts/out/PolicyWallet.sol/PolicyWallet.json", import.meta.url);
const outUrl = new URL("../src/chain/policy-wallet-abi.ts", import.meta.url);

let artifact;
try {
  artifact = JSON.parse(readFileSync(artifactUrl, "utf8"));
} catch (err) {
  console.error(`cannot read ${artifactUrl.pathname}; run \`forge build\` in contracts/ first (${String(err)})`);
  process.exit(1);
}
if (!Array.isArray(artifact.abi)) {
  console.error("artifact has no abi array");
  process.exit(1);
}

const body = JSON.stringify(artifact.abi, null, 2);
const text = `// GENERATED by \`pnpm --filter @horos/adapters abi:generate\` from contracts/out/PolicyWallet.sol/PolicyWallet.json.
// Do not edit by hand; CI regenerates it after \`forge build\` and fails on a diff.
export const policyWalletAbi = ${body} as const;
`;
writeFileSync(outUrl, text);
console.log(`wrote ${outUrl.pathname} (${artifact.abi.length} entries)`);
