// GENERATED by `pnpm --filter @horos/adapters abi:generate` from contracts/out/PolicyWallet.sol/PolicyWallet.json.
// Do not edit by hand; CI regenerates it after `forge build` and fails on a diff.
export const policyWalletAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "roles",
        "type": "tuple",
        "internalType": "struct PolicyWallet.Roles",
        "components": [
          {
            "name": "human",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "payment",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "registrar",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "model",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "rules",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "policy_",
        "type": "tuple",
        "internalType": "struct PolicyWallet.Policy",
        "components": [
          {
            "name": "firstContactCeiling",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletPeriodCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "newPayeeCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "policyPeriodDays",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unpinDelay",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "roleIsContract_",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "MAX_POLICY_PERIOD_DAYS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_UNPIN_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "USDC",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executeUnpin",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      {
        "name": "role",
        "type": "uint8",
        "internalType": "enum PolicyWallet.Role"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "human",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pay",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pendingHuman",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pin",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "policy",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PolicyWallet.Policy",
        "components": [
          {
            "name": "firstContactCeiling",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletPeriodCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "newPayeeCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "policyPeriodDays",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unpinDelay",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "register",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "l",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "releasePin",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "remaining",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PolicyWallet.Remaining",
        "components": [
          {
            "name": "cpRemaining",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletRemaining",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "newPayeeRemaining",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "limit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pinned",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "registered",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "humanSet",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "humanEpoch",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requestUnpin",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reasonHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      {
        "name": "role",
        "type": "uint8",
        "internalType": "enum PolicyWallet.Role"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "roleHolder",
    "inputs": [
      {
        "name": "role",
        "type": "uint8",
        "internalType": "enum PolicyWallet.Role"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "roleIsContract",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setFirstContactCeiling",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLimit",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "l",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setNewPayeeCap",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPolicyPeriod",
    "inputs": [
      {
        "name": "days_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setUnpinDelay",
    "inputs": [
      {
        "name": "seconds_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setWalletPeriodCap",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "tighten",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "l",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expectedEpoch",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newHuman",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "CounterpartyPinned",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CounterpartyRegistered",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "limit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LimitSet",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "oldLimit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newLimit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "humanEpoch",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LimitTightened",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "oldLimit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newLimit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paid",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PinReleased",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PolicyChanged",
    "inputs": [
      {
        "name": "field",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PolicyWallet.PolicyField"
      },
      {
        "name": "oldValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PolicyWallet.Role"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PolicyWallet.Role"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "UnpinRequested",
    "inputs": [
      {
        "name": "counterparty",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "executableAt",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "reasonHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "recordHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CeilingExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DayIndexOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPayee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPolicy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LimitExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NewPayeeCapReached",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPinned",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PayeeIsContract",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Pinned",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RoleConflict",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RoleVacant",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "StaleEpoch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnpinDelayPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnpinNotRequested",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WalletCapExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WithdrawFailed",
    "inputs": []
  }
] as const;
